import torch

if torch.backends.mps.is_available():
    DEVICE = "mps"
elif torch.cuda.is_available():
    DEVICE = "cuda"
else:
    DEVICE = "cpu"

TEST_SIZE = 0.2
RANDOM_SEED = 42
NUM_CLASSES = 4
MAX_SEQ_LEN = 3000
MIN_SEQ_LEN = 500

LEARNING_RATE = 1e-3
BATCH_SIZE = 16
NUM_EPOCHS = 20
NUM_WORKERS = 0

N_FFT = 256
HOP_LENGTH = N_FFT // 4

CONV1_OUT_CHANNELS = 16
CONV1_KERNEL_SIZE = (5, 3)
CONV1_POOL_KERNEL_SIZE = (2, 2)
CONV1_POOL_STRIDE = (2, 2)

CONV2_OUT_CHANNELS = 32
CONV2_KERNEL_SIZE = (5, 3)
CONV2_POOL_KERNEL_SIZE = (2, 2)
CONV2_POOL_STRIDE = (2, 2)

RNN_HIDDEN_SIZE = 64
RNN_NUM_LAYERS = 1

NUM_TRAIN_SAMPLES = 64
NUM_VAL_SAMPLES = 32
