import torch

NUM_CLASSES = 4
MAX_SEQ_LEN = 3000
MIN_SEQ_LEN = 500

LEARNING_RATE = 1e-3
BATCH_SIZE = 16
NUM_EPOCHS = 5
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

N_FFT = 256
HOP_LENGTH = N_FFT // 4

CONV1_OUT_CHANNELS = 16
CONV1_KERNEL_SIZE = (5, 3)
CONV1_POOL_KERNEL_SIZE = (2, 2)
CONV1_POOL_STRIDE = (2, 2)

CONV2_OUT_CHANNELS = 32
CONV2_KERNEL_SIZE = (5, 3)
CONV2_POOL_KERNEL_SIZE = (2, 2)
CONV2_POOL_STRIDE = (2, 2)

RNN_HIDDEN_SIZE = 64
RNN_NUM_LAYERS = 1

NUM_TRAIN_SAMPLES = 64
NUM_VAL_SAMPLES = 32